set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'nightsense/simplifysimplify'
Plugin 'joshdick/onedark.vim'
Plugin 'junegunn/fzf'
Plugin 'chrisbra/Colorizer'

call vundle#end()  

filetype plugin indent on

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

syntax on
set nu
set t_Co=256
let base16colorspace=256

colorscheme onedark
